<?xml version="1.0" encoding="utf-8"?>
<TestRun>
  <Results>
    <UnitTestResult testName="Crashing.AddFailsAfterCrash" outcome="Failed">
      <Output>
        <ErrorInfo>
          <Message>Value of: Add(10, 10)
  Actual: 20
Expected: 1000</Message>
          <StackTrace>at crashingtests.cpp:32 in $(Directory)\sampletests\crashingtests\crashingtests.cpp:line 32</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult testName="Crashing.AddFailsBeforeCrash" outcome="Failed">
      <Output>
        <ErrorInfo>
          <Message>Value of: Add(10, 10)
  Actual: 20
Expected: 1000</Message>
          <StackTrace>at crashingtests.cpp:12 in $(Directory)\sampletests\crashingtests\crashingtests.cpp:line 12</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult testName="Crashing.AddFailsWithÜmlautBeforeCrash" outcome="Failed">
      <Output>
        <ErrorInfo>
          <Message>Value of: 1
Expected: 0
Ümlaut täst</Message>
          <StackTrace>at crashingtests.cpp:17 in $(Directory)\sampletests\crashingtests\crashingtests.cpp:line 17</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult testName="Crashing.AddPassesAfterCrash" outcome="Passed">
      <Output />
    </UnitTestResult>
    <UnitTestResult testName="Crashing.AddPassesBeforeCrash" outcome="NotExecuted">
      <Output>
        <ErrorInfo>
          <Message>reason is probably a crash of test Crashing.TheCrash</Message>
          <StackTrace>at crash suspect in $(Directory)\sampletests\crashingtests\crashingtests.cpp:line 26</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
    <UnitTestResult testName="Crashing.LongRunning" outcome="Passed">
      <Output />
    </UnitTestResult>
    <UnitTestResult testName="Crashing.TheCrash" outcome="Failed">
      <Output>
        <ErrorInfo>
          <Message>!! This is probably the test that crashed !!</Message>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Crashing.AddFailsAfterCrash" storage="$(Directory)\sampletests\${ConfigurationName}\crashingtests.exe">
      <TestMethod name="Crashing.AddFailsAfterCrash" className="Crashing" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter" codeBase="$(Directory)\SampleTests\${ConfigurationName}\CrashingTests.exe" />
    </UnitTest>
    <UnitTest name="Crashing.AddFailsBeforeCrash" storage="$(Directory)\sampletests\${ConfigurationName}\crashingtests.exe">
      <TestMethod name="Crashing.AddFailsBeforeCrash" className="Crashing" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter" codeBase="$(Directory)\SampleTests\${ConfigurationName}\CrashingTests.exe" />
    </UnitTest>
    <UnitTest name="Crashing.AddFailsWithÜmlautBeforeCrash" storage="$(Directory)\sampletests\${ConfigurationName}\crashingtests.exe">
      <TestMethod name="Crashing.AddFailsWithÜmlautBeforeCrash" className="Crashing" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter" codeBase="$(Directory)\SampleTests\${ConfigurationName}\CrashingTests.exe" />
    </UnitTest>
    <UnitTest name="Crashing.AddPassesAfterCrash" storage="$(Directory)\sampletests\${ConfigurationName}\crashingtests.exe">
      <TestMethod name="Crashing.AddPassesAfterCrash" className="Crashing" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter" codeBase="$(Directory)\SampleTests\${ConfigurationName}\CrashingTests.exe" />
    </UnitTest>
    <UnitTest name="Crashing.AddPassesBeforeCrash" storage="$(Directory)\sampletests\${ConfigurationName}\crashingtests.exe">
      <TestMethod name="Crashing.AddPassesBeforeCrash" className="Crashing" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter" codeBase="$(Directory)\SampleTests\${ConfigurationName}\CrashingTests.exe" />
    </UnitTest>
    <UnitTest name="Crashing.LongRunning" storage="$(Directory)\sampletests\${ConfigurationName}\crashingtests.exe">
      <TestMethod name="Crashing.LongRunning" className="Crashing" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter" codeBase="$(Directory)\SampleTests\${ConfigurationName}\CrashingTests.exe" />
    </UnitTest>
    <UnitTest name="Crashing.TheCrash" storage="$(Directory)\sampletests\${ConfigurationName}\crashingtests.exe">
      <TestMethod name="Crashing.TheCrash" className="Crashing" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter" codeBase="$(Directory)\SampleTests\${ConfigurationName}\CrashingTests.exe" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" />
    <TestList name="All Loaded Results" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="7" executed="6" passed="2" failed="4" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output />
  </ResultSummary>
</TestRun>